'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OnsiteCourse
    Public Property CourseID As Integer
    Public Property Location As String
    Public Property Days As String
    Public Property Time As Date

    Public Overridable Property Course As Course

End Class
